### PR TITLE
High Prio: Fix for `Could not create SSL/TLS secure channel`

### PR DESCRIPTION
**Pull request by StefH**
Linked to issue #111

### CODE REVIEW

**Comment by gep13** [comment]
@StefH your changes have been merged, thanks for your contribution :+1:

**Comment by gep13** [comment]
@StefH As I mentioned on the issue linked to this PR, I need to speak with @JakeGinnivan to confirm the process that he follows for shipping GitReleaseNotes.

**Comment by StefH** [comment]
@pbalaga this code is merged

**Comment by henrikgjeriksson** [comment]
@JakeGinnivan @gep13 I'm very interested in updated delivery on chocolatey. But latest update is from 2015 https://chocolatey.org/packages/GitReleaseNotes.Portable
How to release an updated gitreleasenotes on choco? Can I help out?

**Comment by StefH** [comment]
@henrikgjeriksson As a workaround you could maybe use https://github.com/StefH/GitHubReleaseNotes (also on choco)

**Comment by gep13** [comment]
@StefH would you be interested in helping to maintain this project?  If so, I think we can make that happen, and get you the right access that you need.

**Comment by StefH** [comment]
@gep13 Thanks for the suggestion, however the project code and structure is somehow difficult to read and some functionality is broken. Also building in VS2017 is difficult.

So for now I'll stay at my own tool (GitHubReleaseNotes), which unfortunately only has support for GitHub, however for my own use-case this is enough.

**Pull request merged**
